# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zara Leventhal
email: zl@zara-leventhal.com
description: > # this means to ignore newlines until "baseurl:"
  Zara Leventhal is currently an Interactive Digital Media student at Drexel University, enjoying both design and development! In her free time, she sings for the all girls a cappella group, the Drexel TrebleMakers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zara-leventhal.com" # the base hostname & protocol for your site
twitter_username: zaralev
github_username:  zaralev

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 4
paginate_path: "/page:num/"
